---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tatope.tatope.local
  resources:
  - tatopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tatope.tatope.local
  resources:
  - tatopes/finalizers
  verbs:
  - update
- apiGroups:
  - tatope.tatope.local
  resources:
  - tatopes/status
  verbs:
  - get
  - patch
  - update
