# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_get_options import V1GetOptions

class TestV1GetOptions(unittest.TestCase):
    """V1GetOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GetOptions:
        """Test V1GetOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GetOptions`
        """
        model = V1GetOptions()
        if include_optional:
            return V1GetOptions(
                api_version = '',
                kind = '',
                resource_version = ''
            )
        else:
            return V1GetOptions(
        )
        """

    def testV1GetOptions(self):
        """Test V1GetOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
