# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_root_paths import V1RootPaths

class TestV1RootPaths(unittest.TestCase):
    """V1RootPaths unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1RootPaths:
        """Test V1RootPaths
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1RootPaths`
        """
        model = V1RootPaths()
        if include_optional:
            return V1RootPaths(
                paths = [
                    ''
                    ]
            )
        else:
            return V1RootPaths(
                paths = [
                    ''
                    ],
        )
        """

    def testV1RootPaths(self):
        """Test V1RootPaths"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
