# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.runtime_unknown import RuntimeUnknown

class TestRuntimeUnknown(unittest.TestCase):
    """RuntimeUnknown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeUnknown:
        """Test RuntimeUnknown
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeUnknown`
        """
        model = RuntimeUnknown()
        if include_optional:
            return RuntimeUnknown(
                content_encoding = '',
                content_type = '',
                api_version = '',
                kind = ''
            )
        else:
            return RuntimeUnknown(
                content_encoding = '',
                content_type = '',
        )
        """

    def testRuntimeUnknown(self):
        """Test RuntimeUnknown"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
