# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_group_version_for_discovery import V1GroupVersionForDiscovery

class TestV1GroupVersionForDiscovery(unittest.TestCase):
    """V1GroupVersionForDiscovery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GroupVersionForDiscovery:
        """Test V1GroupVersionForDiscovery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GroupVersionForDiscovery`
        """
        model = V1GroupVersionForDiscovery()
        if include_optional:
            return V1GroupVersionForDiscovery(
                group_version = '',
                version = ''
            )
        else:
            return V1GroupVersionForDiscovery(
                group_version = '',
                version = '',
        )
        """

    def testV1GroupVersionForDiscovery(self):
        """Test V1GroupVersionForDiscovery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
