# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_table_options import V1TableOptions

class TestV1TableOptions(unittest.TestCase):
    """V1TableOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TableOptions:
        """Test V1TableOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TableOptions`
        """
        model = V1TableOptions()
        if include_optional:
            return V1TableOptions(
                api_version = '',
                include_object = '',
                kind = ''
            )
        else:
            return V1TableOptions(
        )
        """

    def testV1TableOptions(self):
        """Test V1TableOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
