# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_timestamp import V1Timestamp

class TestV1Timestamp(unittest.TestCase):
    """V1Timestamp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1Timestamp:
        """Test V1Timestamp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1Timestamp`
        """
        model = V1Timestamp()
        if include_optional:
            return V1Timestamp(
                nanos = 56,
                seconds = 56
            )
        else:
            return V1Timestamp(
                nanos = 56,
                seconds = 56,
        )
        """

    def testV1Timestamp(self):
        """Test V1Timestamp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
