# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_label_selector import V1LabelSelector

class TestV1LabelSelector(unittest.TestCase):
    """V1LabelSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1LabelSelector:
        """Test V1LabelSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1LabelSelector`
        """
        model = V1LabelSelector()
        if include_optional:
            return V1LabelSelector(
                match_expressions = [
                    tatope.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                        key = '', 
                        operator = '', 
                        values = [
                            ''
                            ], )
                    ],
                match_labels = {
                    'key' : ''
                    }
            )
        else:
            return V1LabelSelector(
        )
        """

    def testV1LabelSelector(self):
        """Test V1LabelSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
