# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_list_options import V1ListOptions

class TestV1ListOptions(unittest.TestCase):
    """V1ListOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ListOptions:
        """Test V1ListOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ListOptions`
        """
        model = V1ListOptions()
        if include_optional:
            return V1ListOptions(
                allow_watch_bookmarks = True,
                api_version = '',
                var_continue = '',
                field_selector = '',
                kind = '',
                label_selector = '',
                limit = 56,
                resource_version = '',
                resource_version_match = '',
                send_initial_events = True,
                timeout_seconds = 56,
                watch = True
            )
        else:
            return V1ListOptions(
        )
        """

    def testV1ListOptions(self):
        """Test V1ListOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
