# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.k8s_io_apimachinery_pkg_runtime_raw_extension import K8sIoApimachineryPkgRuntimeRawExtension

class TestK8sIoApimachineryPkgRuntimeRawExtension(unittest.TestCase):
    """K8sIoApimachineryPkgRuntimeRawExtension unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> K8sIoApimachineryPkgRuntimeRawExtension:
        """Test K8sIoApimachineryPkgRuntimeRawExtension
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `K8sIoApimachineryPkgRuntimeRawExtension`
        """
        model = K8sIoApimachineryPkgRuntimeRawExtension()
        if include_optional:
            return K8sIoApimachineryPkgRuntimeRawExtension(
            )
        else:
            return K8sIoApimachineryPkgRuntimeRawExtension(
        )
        """

    def testK8sIoApimachineryPkgRuntimeRawExtension(self):
        """Test K8sIoApimachineryPkgRuntimeRawExtension"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
