# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_apply_options import V1ApplyOptions

class TestV1ApplyOptions(unittest.TestCase):
    """V1ApplyOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ApplyOptions:
        """Test V1ApplyOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ApplyOptions`
        """
        model = V1ApplyOptions()
        if include_optional:
            return V1ApplyOptions(
                api_version = '',
                dry_run = [
                    ''
                    ],
                field_manager = '',
                force = True,
                kind = ''
            )
        else:
            return V1ApplyOptions(
                field_manager = '',
                force = True,
        )
        """

    def testV1ApplyOptions(self):
        """Test V1ApplyOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
