# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_table_column_definition import V1TableColumnDefinition

class TestV1TableColumnDefinition(unittest.TestCase):
    """V1TableColumnDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TableColumnDefinition:
        """Test V1TableColumnDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TableColumnDefinition`
        """
        model = V1TableColumnDefinition()
        if include_optional:
            return V1TableColumnDefinition(
                description = '',
                format = '',
                name = '',
                priority = 56,
                type = ''
            )
        else:
            return V1TableColumnDefinition(
                description = '',
                format = '',
                name = '',
                priority = 56,
                type = '',
        )
        """

    def testV1TableColumnDefinition(self):
        """Test V1TableColumnDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
