# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_status_cause import V1StatusCause

class TestV1StatusCause(unittest.TestCase):
    """V1StatusCause unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1StatusCause:
        """Test V1StatusCause
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1StatusCause`
        """
        model = V1StatusCause()
        if include_optional:
            return V1StatusCause(
                var_field = '',
                message = '',
                reason = ''
            )
        else:
            return V1StatusCause(
        )
        """

    def testV1StatusCause(self):
        """Test V1StatusCause"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
