# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_list import V1List

class TestV1List(unittest.TestCase):
    """V1List unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1List:
        """Test V1List
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1List`
        """
        model = V1List()
        if include_optional:
            return V1List(
                api_version = '',
                items = [
                    tatope.models.k8s/io/apimachinery/pkg/runtime/raw_extension.k8s.io.apimachinery.pkg.runtime.RawExtension()
                    ],
                kind = '',
                metadata = tatope.models.v1/list_meta.v1.ListMeta(
                    continue = '', 
                    remaining_item_count = 56, 
                    resource_version = '', 
                    self_link = '', )
            )
        else:
            return V1List(
                items = [
                    tatope.models.k8s/io/apimachinery/pkg/runtime/raw_extension.k8s.io.apimachinery.pkg.runtime.RawExtension()
                    ],
        )
        """

    def testV1List(self):
        """Test V1List"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
