# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.tat_ope_list import TatOpeList

class TestTatOpeList(unittest.TestCase):
    """TatOpeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TatOpeList:
        """Test TatOpeList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TatOpeList`
        """
        model = TatOpeList()
        if include_optional:
            return TatOpeList(
                api_version = '',
                items = [
                    tatope.models.tat_ope.TatOpe(
                        api_version = '', 
                        kind = '', 
                        metadata = None, 
                        spec = tatope.models.tat_ope_spec.TatOpeSpec(
                            foo = '', 
                            hoge = '', 
                            ports = [
                                56
                                ], ), 
                        status = tatope.models.tat_ope_status.TatOpeStatus(
                            state = '', ), )
                    ],
                kind = '',
                metadata = None
            )
        else:
            return TatOpeList(
                items = [
                    tatope.models.tat_ope.TatOpe(
                        api_version = '', 
                        kind = '', 
                        metadata = None, 
                        spec = tatope.models.tat_ope_spec.TatOpeSpec(
                            foo = '', 
                            hoge = '', 
                            ports = [
                                56
                                ], ), 
                        status = tatope.models.tat_ope_status.TatOpeStatus(
                            state = '', ), )
                    ],
        )
        """

    def testTatOpeList(self):
        """Test TatOpeList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
