# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.tat_ope import TatOpe

class TestTatOpe(unittest.TestCase):
    """TatOpe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TatOpe:
        """Test TatOpe
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TatOpe`
        """
        model = TatOpe()
        if include_optional:
            return TatOpe(
                api_version = '',
                kind = '',
                metadata = None,
                spec = tatope.models.tat_ope_spec.TatOpeSpec(
                    foo = '', 
                    ports = [
                        56
                        ], ),
                status = tatope.models.tat_ope_status.TatOpeStatus(
                    state = '', )
            )
        else:
            return TatOpe(
        )
        """

    def testTatOpe(self):
        """Test TatOpe"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
