# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_group_version import V1GroupVersion

class TestV1GroupVersion(unittest.TestCase):
    """V1GroupVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GroupVersion:
        """Test V1GroupVersion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GroupVersion`
        """
        model = V1GroupVersion()
        if include_optional:
            return V1GroupVersion(
                group = '',
                version = ''
            )
        else:
            return V1GroupVersion(
                group = '',
                version = '',
        )
        """

    def testV1GroupVersion(self):
        """Test V1GroupVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
