# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_patch_options import V1PatchOptions

class TestV1PatchOptions(unittest.TestCase):
    """V1PatchOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PatchOptions:
        """Test V1PatchOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PatchOptions`
        """
        model = V1PatchOptions()
        if include_optional:
            return V1PatchOptions(
                api_version = '',
                dry_run = [
                    ''
                    ],
                field_manager = '',
                field_validation = '',
                force = True,
                kind = ''
            )
        else:
            return V1PatchOptions(
        )
        """

    def testV1PatchOptions(self):
        """Test V1PatchOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
