# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_field_selector_requirement import V1FieldSelectorRequirement

class TestV1FieldSelectorRequirement(unittest.TestCase):
    """V1FieldSelectorRequirement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FieldSelectorRequirement:
        """Test V1FieldSelectorRequirement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FieldSelectorRequirement`
        """
        model = V1FieldSelectorRequirement()
        if include_optional:
            return V1FieldSelectorRequirement(
                key = '',
                operator = '',
                values = [
                    ''
                    ]
            )
        else:
            return V1FieldSelectorRequirement(
                key = '',
                operator = '',
        )
        """

    def testV1FieldSelectorRequirement(self):
        """Test V1FieldSelectorRequirement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
