# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.k8s_io_apimachinery_pkg_runtime_unknown import K8sIoApimachineryPkgRuntimeUnknown

class TestK8sIoApimachineryPkgRuntimeUnknown(unittest.TestCase):
    """K8sIoApimachineryPkgRuntimeUnknown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> K8sIoApimachineryPkgRuntimeUnknown:
        """Test K8sIoApimachineryPkgRuntimeUnknown
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `K8sIoApimachineryPkgRuntimeUnknown`
        """
        model = K8sIoApimachineryPkgRuntimeUnknown()
        if include_optional:
            return K8sIoApimachineryPkgRuntimeUnknown(
                content_encoding = '',
                content_type = '',
                api_version = '',
                kind = ''
            )
        else:
            return K8sIoApimachineryPkgRuntimeUnknown(
                content_encoding = '',
                content_type = '',
        )
        """

    def testK8sIoApimachineryPkgRuntimeUnknown(self):
        """Test K8sIoApimachineryPkgRuntimeUnknown"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
