# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_group_kind import V1GroupKind

class TestV1GroupKind(unittest.TestCase):
    """V1GroupKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GroupKind:
        """Test V1GroupKind
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GroupKind`
        """
        model = V1GroupKind()
        if include_optional:
            return V1GroupKind(
                group = '',
                kind = ''
            )
        else:
            return V1GroupKind(
                group = '',
                kind = '',
        )
        """

    def testV1GroupKind(self):
        """Test V1GroupKind"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
