# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.v1_table_row_condition import V1TableRowCondition

class TestV1TableRowCondition(unittest.TestCase):
    """V1TableRowCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TableRowCondition:
        """Test V1TableRowCondition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TableRowCondition`
        """
        model = V1TableRowCondition()
        if include_optional:
            return V1TableRowCondition(
                message = '',
                reason = '',
                status = '',
                type = ''
            )
        else:
            return V1TableRowCondition(
                status = '',
                type = '',
        )
        """

    def testV1TableRowCondition(self):
        """Test V1TableRowCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
