# coding: utf-8

"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tatope.models.tat_ope_ex_spec import TatOpeExSpec

class TestTatOpeExSpec(unittest.TestCase):
    """TatOpeExSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TatOpeExSpec:
        """Test TatOpeExSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TatOpeExSpec`
        """
        model = TatOpeExSpec()
        if include_optional:
            return TatOpeExSpec(
                bar = '',
                foo = ''
            )
        else:
            return TatOpeExSpec(
        )
        """

    def testTatOpeExSpec(self):
        """Test TatOpeExSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
