# coding: utf-8

# flake8: noqa
"""
    tatoperator

    Python SDK for Tat-Operator

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from tatope.models.k8s_io_apimachinery_pkg_runtime_type_meta import K8sIoApimachineryPkgRuntimeTypeMeta
from tatope.models.k8s_io_apimachinery_pkg_runtime_unknown import K8sIoApimachineryPkgRuntimeUnknown
from tatope.models.k8s_io_apimachinery_pkg_version_info import K8sIoApimachineryPkgVersionInfo
from tatope.models.tat_ope import TatOpe
from tatope.models.tat_ope_ex import TatOpeEx
from tatope.models.tat_ope_ex_list import TatOpeExList
from tatope.models.tat_ope_ex_spec import TatOpeExSpec
from tatope.models.tat_ope_ex_status import TatOpeExStatus
from tatope.models.tat_ope_list import TatOpeList
from tatope.models.tat_ope_spec import TatOpeSpec
from tatope.models.tat_ope_status import TatOpeStatus
from tatope.models.v1_api_group import V1APIGroup
from tatope.models.v1_api_group_list import V1APIGroupList
from tatope.models.v1_api_resource import V1APIResource
from tatope.models.v1_api_resource_list import V1APIResourceList
from tatope.models.v1_api_versions import V1APIVersions
from tatope.models.v1_apply_options import V1ApplyOptions
from tatope.models.v1_condition import V1Condition
from tatope.models.v1_create_options import V1CreateOptions
from tatope.models.v1_delete_options import V1DeleteOptions
from tatope.models.v1_field_selector_requirement import V1FieldSelectorRequirement
from tatope.models.v1_get_options import V1GetOptions
from tatope.models.v1_group_kind import V1GroupKind
from tatope.models.v1_group_resource import V1GroupResource
from tatope.models.v1_group_version import V1GroupVersion
from tatope.models.v1_group_version_for_discovery import V1GroupVersionForDiscovery
from tatope.models.v1_group_version_kind import V1GroupVersionKind
from tatope.models.v1_group_version_resource import V1GroupVersionResource
from tatope.models.v1_internal_event import V1InternalEvent
from tatope.models.v1_label_selector import V1LabelSelector
from tatope.models.v1_label_selector_requirement import V1LabelSelectorRequirement
from tatope.models.v1_list import V1List
from tatope.models.v1_list_meta import V1ListMeta
from tatope.models.v1_list_options import V1ListOptions
from tatope.models.v1_managed_fields_entry import V1ManagedFieldsEntry
from tatope.models.v1_object_meta import V1ObjectMeta
from tatope.models.v1_owner_reference import V1OwnerReference
from tatope.models.v1_partial_object_metadata import V1PartialObjectMetadata
from tatope.models.v1_partial_object_metadata_list import V1PartialObjectMetadataList
from tatope.models.v1_patch_options import V1PatchOptions
from tatope.models.v1_preconditions import V1Preconditions
from tatope.models.v1_root_paths import V1RootPaths
from tatope.models.v1_server_address_by_client_cidr import V1ServerAddressByClientCIDR
from tatope.models.v1_status import V1Status
from tatope.models.v1_status_cause import V1StatusCause
from tatope.models.v1_status_details import V1StatusDetails
from tatope.models.v1_table import V1Table
from tatope.models.v1_table_column_definition import V1TableColumnDefinition
from tatope.models.v1_table_options import V1TableOptions
from tatope.models.v1_table_row import V1TableRow
from tatope.models.v1_table_row_condition import V1TableRowCondition
from tatope.models.v1_timestamp import V1Timestamp
from tatope.models.v1_type_meta import V1TypeMeta
from tatope.models.v1_update_options import V1UpdateOptions
from tatope.models.v1_watch_event import V1WatchEvent
